import 'exercise.dart';

/// Every exercise the plan-generator can pick from. One hundred entries,
/// grouped by starting position for readability. IDs are stable so a saved
/// plan can be reloaded even if the list is reordered — never rename or
/// recycle an ID.
const exerciseCatalogue = <Exercise>[
  // =========================================================================
  // STANDING (30) — no floor contact, drives the "All Standing" preference.
  // =========================================================================
  Exercise(
    id: 'stand_high_knees',
    name: 'High Knees',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.fullBody,
    secondary: {ExerciseMuscle.quads, ExerciseMuscle.coreAnterior},
    movements: {ExerciseMovement.cardio, ExerciseMovement.jump},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    highImpact: true,
    cues: 'Drive knees to hip height, quick light feet.',
  ),
  Exercise(
    id: 'stand_march',
    name: 'March in Place',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.fullBody,
    secondary: {ExerciseMuscle.hipMobility},
    movements: {ExerciseMovement.cardio, ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 45,
    cues: 'Tall posture, swing arms in opposition.',
  ),
  Exercise(
    id: 'stand_calf_raise',
    name: 'Standing Calf Raises',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.calves,
    movements: {ExerciseMovement.push},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 20,
    cues: 'Rise to the ball of your foot, pause, lower slowly.',
  ),
  Exercise(
    id: 'stand_arm_circles',
    name: 'Arm Circles',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.shoulders,
    movements: {ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Small then big, forward then back.',
  ),
  Exercise(
    id: 'stand_twist_punches',
    name: 'Standing Twist Punches',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.obliques,
    secondary: {ExerciseMuscle.shoulders},
    movements: {ExerciseMovement.twist, ExerciseMovement.cardio},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Rotate from the ribcage, hips stay square.',
  ),
  Exercise(
    id: 'stand_bicycle',
    name: 'Standing Bicycle Crunch',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.obliques,
    secondary: {ExerciseMuscle.coreAnterior},
    movements: {ExerciseMovement.twist},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 20,
    cues: 'Elbow to opposite knee, exhale on the crunch.',
  ),
  Exercise(
    id: 'stand_oblique_crunch',
    name: 'Standing Oblique Crunches',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.obliques,
    movements: {ExerciseMovement.twist},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 16,
    cues: 'Bring elbow and same-side knee together, side of the body.',
  ),
  Exercise(
    id: 'stand_front_leg_raise',
    name: 'Standing Front Leg Raise',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.coreAnterior,
    secondary: {ExerciseMuscle.quads},
    movements: {ExerciseMovement.kick},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Stand tall, lift the leg with control — no swing.',
  ),
  Exercise(
    id: 'stand_side_leg_raise',
    name: 'Standing Side Leg Raise',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.glutes,
    movements: {ExerciseMovement.kick},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 15,
    cues: 'Lift straight out to the side, keep hips level.',
  ),
  Exercise(
    id: 'stand_rear_leg_raise',
    name: 'Standing Rear Leg Raise',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.glutes,
    movements: {ExerciseMovement.hinge},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 15,
    cues: 'Squeeze the glute, no arching the lower back.',
  ),
  Exercise(
    id: 'stand_wall_pushup',
    name: 'Wall Push-Ups',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.chest,
    secondary: {ExerciseMuscle.arms, ExerciseMuscle.shoulders},
    movements: {ExerciseMovement.push},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 15,
    cues: 'Hands wider than shoulders, ribs stay knit.',
  ),
  Exercise(
    id: 'stand_wall_sit',
    name: 'Wall Sit',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.quads,
    secondary: {ExerciseMuscle.glutes},
    movements: {ExerciseMovement.hold},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Thighs parallel to the ground, knees over ankles.',
  ),
  Exercise(
    id: 'stand_march_twist',
    name: 'March with Twist',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.obliques,
    secondary: {ExerciseMuscle.fullBody},
    movements: {ExerciseMovement.twist, ExerciseMovement.cardio},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Elbow reaches to opposite knee each step.',
  ),
  Exercise(
    id: 'stand_jumping_jacks',
    name: 'Jumping Jacks',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.fullBody,
    movements: {ExerciseMovement.cardio, ExerciseMovement.jump},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    highImpact: true,
    cues: 'Land soft, arms fully overhead at the top.',
  ),
  Exercise(
    id: 'stand_skater_hops',
    name: 'Skater Hops',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.glutes,
    secondary: {ExerciseMuscle.quads},
    movements: {ExerciseMovement.cardio, ExerciseMovement.jump},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    highImpact: true,
    cues: 'Bound side to side, stick the landing on one leg.',
  ),
  Exercise(
    id: 'stand_torso_rotation',
    name: 'Torso Rotations',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.spineMobility,
    movements: {ExerciseMovement.mobility, ExerciseMovement.twist},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Feet planted, swing arms and let the torso follow.',
  ),
  Exercise(
    id: 'stand_y_raise',
    name: 'Standing Y-Raise',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.upperBack,
    secondary: {ExerciseMuscle.shoulders},
    movements: {ExerciseMovement.pull},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Hinge forward slightly, sweep arms into a Y overhead.',
  ),
  Exercise(
    id: 'stand_band_row',
    name: 'Standing Band Row',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.upperBack,
    secondary: {ExerciseMuscle.arms},
    movements: {ExerciseMovement.pull},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    needsBand: true,
    cues: 'Squeeze shoulder blades together, elbows brush ribs.',
  ),
  Exercise(
    id: 'stand_cross_punches',
    name: 'Cross-Body Punches',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.shoulders,
    secondary: {ExerciseMuscle.obliques},
    movements: {ExerciseMovement.cardio, ExerciseMovement.twist},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Rotate through the hip, exhale on each punch.',
  ),
  Exercise(
    id: 'stand_front_kick',
    name: 'Standing Front Kicks',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.quads,
    secondary: {ExerciseMuscle.glutes, ExerciseMuscle.coreAnterior},
    movements: {ExerciseMovement.kick, ExerciseMovement.cardio},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 20,
    cues: 'Chamber the knee, snap the leg out, retract.',
  ),
  Exercise(
    id: 'stand_side_kick',
    name: 'Standing Side Kicks',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.glutes,
    movements: {ExerciseMovement.kick, ExerciseMovement.cardio},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 20,
    cues: 'Chamber, kick to the side, land soft.',
  ),
  Exercise(
    id: 'stand_rear_kick',
    name: 'Standing Rear Kicks',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.glutes,
    movements: {ExerciseMovement.kick},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 16,
    cues: 'Hinge slightly, drive heel back and up.',
  ),
  Exercise(
    id: 'stand_knee_elbow_crunch',
    name: 'Standing Knee-to-Elbow Crunch',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.coreAnterior,
    movements: {ExerciseMovement.twist},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 20,
    cues: 'Same-side elbow meets same-side knee.',
  ),
  Exercise(
    id: 'stand_windmill',
    name: 'Standing Windmill',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.obliques,
    secondary: {ExerciseMuscle.spineMobility},
    movements: {ExerciseMovement.twist, ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 16,
    cues: 'Wide stance, hand to opposite foot, rotate the ribs.',
  ),
  Exercise(
    id: 'stand_toe_touches',
    name: 'Standing Toe Touches',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.hamstrings,
    secondary: {ExerciseMuscle.spineMobility},
    movements: {ExerciseMovement.mobility, ExerciseMovement.hinge},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Soft knees, hinge from the hips, no rounding.',
  ),
  Exercise(
    id: 'stand_hip_circles',
    name: 'Standing Hip Circles',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.hipMobility,
    movements: {ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Big lazy circles at the hip joint, both directions.',
  ),
  Exercise(
    id: 'stand_shadow_box',
    name: 'Shadow Boxing',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.fullBody,
    secondary: {ExerciseMuscle.shoulders, ExerciseMuscle.obliques},
    movements: {ExerciseMovement.cardio},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 45,
    cues: 'Stay light on your feet, mix jab-cross-hook.',
  ),
  Exercise(
    id: 'stand_halo',
    name: 'Standing Halo',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.shoulders,
    secondary: {ExerciseMuscle.coreAnterior},
    movements: {ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 10,
    cues: 'Hands together, circle the head slowly.',
  ),
  Exercise(
    id: 'stand_bear_hug_stretch',
    name: 'Bear Hug Stretch',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.upperBack,
    movements: {ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 20,
    cues: 'Wrap arms around your ribs, expand the upper back.',
  ),
  Exercise(
    id: 'stand_tricep_ext',
    name: 'Standing Tricep Extension',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.arms,
    movements: {ExerciseMovement.push},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 15,
    needsBand: true,
    cues: 'Elbows tucked, only the forearm moves.',
  ),

  // =========================================================================
  // SQUAT / LUNGE STANCE (12) — filtered out by "No Squat".
  // =========================================================================
  Exercise(
    id: 'squat_bodyweight',
    name: 'Bodyweight Squat',
    position: ExercisePosition.squatStance,
    primary: ExerciseMuscle.quads,
    secondary: {ExerciseMuscle.glutes},
    movements: {ExerciseMovement.squat},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 15,
    cues: 'Sit hips back, knees track over toes.',
  ),
  Exercise(
    id: 'squat_sumo',
    name: 'Sumo Squat',
    position: ExercisePosition.squatStance,
    primary: ExerciseMuscle.innerThighs,
    secondary: {ExerciseMuscle.glutes},
    movements: {ExerciseMovement.squat},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 15,
    cues: 'Wide stance, toes turned out, chest tall.',
  ),
  Exercise(
    id: 'squat_pulse',
    name: 'Squat Pulses',
    position: ExercisePosition.squatStance,
    primary: ExerciseMuscle.quads,
    secondary: {ExerciseMuscle.glutes},
    movements: {ExerciseMovement.squat, ExerciseMovement.hold},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Stay low, short two-inch pulses.',
  ),
  Exercise(
    id: 'squat_hold',
    name: 'Squat Hold',
    position: ExercisePosition.squatStance,
    primary: ExerciseMuscle.quads,
    movements: {ExerciseMovement.squat, ExerciseMovement.hold},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Thighs parallel, weight in your heels.',
  ),
  Exercise(
    id: 'squat_calf_raise',
    name: 'Squat to Calf Raise',
    position: ExercisePosition.squatStance,
    primary: ExerciseMuscle.quads,
    secondary: {ExerciseMuscle.calves, ExerciseMuscle.glutes},
    movements: {ExerciseMovement.squat},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Stand up, rise onto the balls of your feet.',
  ),
  Exercise(
    id: 'squat_jump',
    name: 'Squat Jumps',
    position: ExercisePosition.squatStance,
    primary: ExerciseMuscle.quads,
    secondary: {ExerciseMuscle.glutes, ExerciseMuscle.fullBody},
    movements: {ExerciseMovement.squat, ExerciseMovement.jump, ExerciseMovement.cardio},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    highImpact: true,
    cues: 'Explode up, land soft into the next squat.',
  ),
  Exercise(
    id: 'lunge_split',
    name: 'Split Squat',
    position: ExercisePosition.lungeStance,
    primary: ExerciseMuscle.quads,
    secondary: {ExerciseMuscle.glutes},
    movements: {ExerciseMovement.lunge, ExerciseMovement.squat},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 10,
    cues: 'Back knee lowers straight down, torso stays tall.',
  ),
  Exercise(
    id: 'lunge_reverse',
    name: 'Reverse Lunge',
    position: ExercisePosition.lungeStance,
    primary: ExerciseMuscle.glutes,
    secondary: {ExerciseMuscle.quads},
    movements: {ExerciseMovement.lunge},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Step long behind, front knee tracks over the shoelaces.',
  ),
  Exercise(
    id: 'lunge_forward',
    name: 'Forward Lunge',
    position: ExercisePosition.lungeStance,
    primary: ExerciseMuscle.glutes,
    secondary: {ExerciseMuscle.quads},
    movements: {ExerciseMovement.lunge},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Step out, drop the back knee, push back through the heel.',
  ),
  Exercise(
    id: 'lunge_lateral',
    name: 'Lateral Lunge',
    position: ExercisePosition.lungeStance,
    primary: ExerciseMuscle.innerThighs,
    secondary: {ExerciseMuscle.glutes},
    movements: {ExerciseMovement.lunge, ExerciseMovement.squat},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 10,
    cues: 'Step wide, sit into the bent-knee hip.',
  ),
  Exercise(
    id: 'lunge_curtsy',
    name: 'Curtsy Lunge',
    position: ExercisePosition.lungeStance,
    primary: ExerciseMuscle.glutes,
    secondary: {ExerciseMuscle.quads},
    movements: {ExerciseMovement.lunge},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 10,
    cues: 'Step behind and across, keep chest up.',
  ),
  Exercise(
    id: 'lunge_jumping',
    name: 'Jumping Lunges',
    position: ExercisePosition.lungeStance,
    primary: ExerciseMuscle.quads,
    secondary: {ExerciseMuscle.glutes, ExerciseMuscle.fullBody},
    movements: {ExerciseMovement.lunge, ExerciseMovement.jump, ExerciseMovement.cardio},
    difficulty: ExerciseDifficulty.advanced,
    unit: ExerciseUnit.reps,
    baseAmount: 10,
    highImpact: true,
    cues: 'Switch legs in the air, land soft.',
  ),

  // =========================================================================
  // PRONE (15) — filtered out by "No Prone".
  // =========================================================================
  Exercise(
    id: 'prone_pushup',
    name: 'Push-Up',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.chest,
    secondary: {ExerciseMuscle.arms, ExerciseMuscle.shoulders, ExerciseMuscle.coreAnterior},
    movements: {ExerciseMovement.push},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 10,
    cues: 'Full plank, elbows 45°, chest kisses the floor.',
  ),
  Exercise(
    id: 'prone_knee_pushup',
    name: 'Knee Push-Up',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.chest,
    secondary: {ExerciseMuscle.arms},
    movements: {ExerciseMovement.push},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Long line from knees to head, ribs stay knit.',
  ),
  Exercise(
    id: 'prone_wide_pushup',
    name: 'Wide Push-Up',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.chest,
    secondary: {ExerciseMuscle.shoulders},
    movements: {ExerciseMovement.push},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 10,
    cues: 'Hands wider than shoulders, elbows flare a bit.',
  ),
  Exercise(
    id: 'prone_diamond_pushup',
    name: 'Diamond Push-Up',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.arms,
    secondary: {ExerciseMuscle.chest},
    movements: {ExerciseMovement.push},
    difficulty: ExerciseDifficulty.advanced,
    unit: ExerciseUnit.reps,
    baseAmount: 8,
    cues: 'Thumbs and index touch, elbows brush ribs.',
  ),
  Exercise(
    id: 'prone_incline_pushup',
    name: 'Incline Push-Up',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.chest,
    secondary: {ExerciseMuscle.arms},
    movements: {ExerciseMovement.push},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Hands on a couch or step, treat it like a regular push-up.',
  ),
  Exercise(
    id: 'prone_decline_pushup',
    name: 'Decline Push-Up',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.shoulders,
    secondary: {ExerciseMuscle.chest},
    movements: {ExerciseMovement.push},
    difficulty: ExerciseDifficulty.advanced,
    unit: ExerciseUnit.reps,
    baseAmount: 8,
    cues: 'Feet elevated on a step, hips level.',
  ),
  Exercise(
    id: 'prone_cobra',
    name: 'Cobra Stretch',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.spineMobility,
    movements: {ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 20,
    cues: 'Palms under shoulders, lift chest, shoulders down.',
  ),
  Exercise(
    id: 'prone_superman',
    name: 'Superman',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.lowerBack,
    secondary: {ExerciseMuscle.glutes, ExerciseMuscle.upperBack},
    movements: {ExerciseMovement.hinge},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Lift arms and legs, gaze at the mat.',
  ),
  Exercise(
    id: 'prone_superman_pulse',
    name: 'Superman Pulses',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.lowerBack,
    secondary: {ExerciseMuscle.glutes},
    movements: {ExerciseMovement.hold, ExerciseMovement.hinge},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Hold the lift, small pulses up and down.',
  ),
  Exercise(
    id: 'prone_ytw',
    name: 'Prone Y-T-W',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.upperBack,
    secondary: {ExerciseMuscle.shoulders},
    movements: {ExerciseMovement.pull},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 8,
    cues: 'Sweep the arms into Y, then T, then W. Squeeze the mid back.',
  ),
  Exercise(
    id: 'prone_swimmers',
    name: 'Swimmers',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.lowerBack,
    secondary: {ExerciseMuscle.upperBack, ExerciseMuscle.glutes},
    movements: {ExerciseMovement.cardio, ExerciseMovement.hinge},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Opposite arm and leg, alternate like a flutter.',
  ),
  Exercise(
    id: 'prone_forearm_plank',
    name: 'Forearm Plank',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.coreAnterior,
    secondary: {ExerciseMuscle.shoulders},
    movements: {ExerciseMovement.plank, ExerciseMovement.hold},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Elbows under shoulders, ribs down, glutes on.',
  ),
  Exercise(
    id: 'prone_plank_shoulder_tap',
    name: 'Plank Shoulder Taps',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.coreAnterior,
    secondary: {ExerciseMuscle.shoulders, ExerciseMuscle.obliques},
    movements: {ExerciseMovement.plank},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 20,
    cues: 'High plank, tap opposite shoulder, hips stay still.',
  ),
  Exercise(
    id: 'prone_plank_hip_dip',
    name: 'Plank Hip Dips',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.obliques,
    secondary: {ExerciseMuscle.coreAnterior},
    movements: {ExerciseMovement.plank, ExerciseMovement.twist},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 16,
    cues: 'Rotate the pelvis side to side, control the descent.',
  ),
  Exercise(
    id: 'prone_up_down_plank',
    name: 'Up-Down Plank',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.coreAnterior,
    secondary: {ExerciseMuscle.arms, ExerciseMuscle.shoulders},
    movements: {ExerciseMovement.plank, ExerciseMovement.push},
    difficulty: ExerciseDifficulty.advanced,
    unit: ExerciseUnit.reps,
    baseAmount: 10,
    cues: 'From forearm to hand, one arm at a time. Hips still.',
  ),

  // =========================================================================
  // SUPINE (15)
  // =========================================================================
  Exercise(
    id: 'sup_crunch',
    name: 'Crunches',
    position: ExercisePosition.supine,
    primary: ExerciseMuscle.coreAnterior,
    movements: {ExerciseMovement.plank},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 20,
    cues: 'Peel the shoulder blades off, exhale on the crunch.',
  ),
  Exercise(
    id: 'sup_bicycle_crunch',
    name: 'Bicycle Crunches',
    position: ExercisePosition.supine,
    primary: ExerciseMuscle.obliques,
    secondary: {ExerciseMuscle.coreAnterior},
    movements: {ExerciseMovement.twist},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 20,
    cues: 'Elbow to opposite knee, extend the other leg long.',
  ),
  Exercise(
    id: 'sup_reverse_crunch',
    name: 'Reverse Crunches',
    position: ExercisePosition.supine,
    primary: ExerciseMuscle.coreAnterior,
    movements: {ExerciseMovement.hinge},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 15,
    cues: 'Curl the pelvis toward the ribs, feet fly up.',
  ),
  Exercise(
    id: 'sup_v_up',
    name: 'V-Ups',
    position: ExercisePosition.supine,
    primary: ExerciseMuscle.coreAnterior,
    movements: {ExerciseMovement.plank},
    difficulty: ExerciseDifficulty.advanced,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Fingertips meet toes at the top, control down.',
  ),
  Exercise(
    id: 'sup_leg_raise',
    name: 'Leg Raises',
    position: ExercisePosition.supine,
    primary: ExerciseMuscle.coreAnterior,
    movements: {ExerciseMovement.hinge},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Lower back stays glued to the mat.',
  ),
  Exercise(
    id: 'sup_flutter_kick',
    name: 'Flutter Kicks',
    position: ExercisePosition.supine,
    primary: ExerciseMuscle.coreAnterior,
    movements: {ExerciseMovement.cardio, ExerciseMovement.hold},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Small quick kicks, lower back pressed down.',
  ),
  Exercise(
    id: 'sup_russian_twist',
    name: 'Russian Twists',
    position: ExercisePosition.sitting,
    primary: ExerciseMuscle.obliques,
    movements: {ExerciseMovement.twist},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 20,
    cues: 'Lean back 45°, rotate ribs, tap the floor.',
  ),
  Exercise(
    id: 'sup_dead_bug',
    name: 'Dead Bug',
    position: ExercisePosition.supine,
    primary: ExerciseMuscle.coreAnterior,
    movements: {ExerciseMovement.plank},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Opposite arm and leg reach out, ribs stay heavy.',
  ),
  Exercise(
    id: 'sup_glute_bridge',
    name: 'Glute Bridge',
    position: ExercisePosition.supine,
    primary: ExerciseMuscle.glutes,
    secondary: {ExerciseMuscle.hamstrings},
    movements: {ExerciseMovement.hinge},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 15,
    cues: 'Drive through the heels, squeeze the glutes at the top.',
  ),
  Exercise(
    id: 'sup_single_leg_bridge',
    name: 'Single-Leg Glute Bridge',
    position: ExercisePosition.supine,
    primary: ExerciseMuscle.glutes,
    secondary: {ExerciseMuscle.hamstrings},
    movements: {ExerciseMovement.hinge},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 10,
    cues: 'One foot planted, opposite leg long, drive up level.',
  ),
  Exercise(
    id: 'sup_bridge_march',
    name: 'Bridge March',
    position: ExercisePosition.supine,
    primary: ExerciseMuscle.glutes,
    secondary: {ExerciseMuscle.coreAnterior},
    movements: {ExerciseMovement.hold},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 16,
    cues: 'Hold the bridge, alternate lifting one foot.',
  ),
  Exercise(
    id: 'sup_hip_thrust',
    name: 'Hip Thruster',
    position: ExercisePosition.supine,
    primary: ExerciseMuscle.glutes,
    movements: {ExerciseMovement.hinge},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 15,
    cues: 'Shoulders elevated on a couch, chin tucked, drive hips up.',
  ),
  Exercise(
    id: 'sup_toe_touch',
    name: 'Supine Toe Touch',
    position: ExercisePosition.supine,
    primary: ExerciseMuscle.coreAnterior,
    movements: {ExerciseMovement.plank},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 15,
    cues: 'Legs straight up, reach fingertips to toes.',
  ),
  Exercise(
    id: 'sup_scissor',
    name: 'Scissor Kicks',
    position: ExercisePosition.supine,
    primary: ExerciseMuscle.coreAnterior,
    movements: {ExerciseMovement.cardio},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Cross one leg over the other, alternate.',
  ),
  Exercise(
    id: 'sup_hollow_hold',
    name: 'Hollow Hold',
    position: ExercisePosition.supine,
    primary: ExerciseMuscle.coreAnterior,
    movements: {ExerciseMovement.hold},
    difficulty: ExerciseDifficulty.advanced,
    unit: ExerciseUnit.seconds,
    baseAmount: 20,
    cues: 'Ribs down, arms overhead, legs low. Banana shape.',
  ),

  // =========================================================================
  // KNEELING / BEAR STANCE (13) — filtered by "No Kneeling".
  // =========================================================================
  Exercise(
    id: 'knee_bird_dog',
    name: 'Bird Dog',
    position: ExercisePosition.kneeling,
    primary: ExerciseMuscle.coreAnterior,
    secondary: {ExerciseMuscle.glutes, ExerciseMuscle.upperBack},
    movements: {ExerciseMovement.plank},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Opposite arm and leg reach long, back stays flat.',
  ),
  Exercise(
    id: 'knee_bird_dog_crunch',
    name: 'Bird Dog Crunch',
    position: ExercisePosition.kneeling,
    primary: ExerciseMuscle.obliques,
    secondary: {ExerciseMuscle.coreAnterior},
    movements: {ExerciseMovement.plank, ExerciseMovement.twist},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Crunch elbow to opposite knee under the belly, then reach out.',
  ),
  Exercise(
    id: 'knee_cat_cow',
    name: 'Cat-Cow',
    position: ExercisePosition.kneeling,
    primary: ExerciseMuscle.spineMobility,
    movements: {ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 10,
    cues: 'Round through the spine, then arch — one bone at a time.',
  ),
  Exercise(
    id: 'knee_hip_circle',
    name: 'Kneeling Hip Circles',
    position: ExercisePosition.kneeling,
    primary: ExerciseMuscle.hipMobility,
    movements: {ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 10,
    cues: 'On hands and knees, draw big circles with the knee.',
  ),
  Exercise(
    id: 'knee_side_kick',
    name: 'Kneeling Side Kick',
    position: ExercisePosition.kneeling,
    primary: ExerciseMuscle.glutes,
    movements: {ExerciseMovement.kick},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'From all fours, kick straight to the side, ribs stay knit.',
  ),
  Exercise(
    id: 'knee_fire_hydrant',
    name: 'Fire Hydrants',
    position: ExercisePosition.kneeling,
    primary: ExerciseMuscle.glutes,
    movements: {ExerciseMovement.kick},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 15,
    cues: 'Knee opens to the side, hips stay square.',
  ),
  Exercise(
    id: 'knee_donkey_kick',
    name: 'Donkey Kicks',
    position: ExercisePosition.kneeling,
    primary: ExerciseMuscle.glutes,
    movements: {ExerciseMovement.kick, ExerciseMovement.hinge},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 15,
    cues: 'Drive the sole of the foot to the ceiling, squeeze the glute.',
  ),
  Exercise(
    id: 'knee_pushup_side_plank',
    name: 'Kneeling Push-Up to Side Plank',
    position: ExercisePosition.kneeling,
    primary: ExerciseMuscle.chest,
    secondary: {ExerciseMuscle.obliques, ExerciseMuscle.arms},
    movements: {ExerciseMovement.push, ExerciseMovement.plank},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 10,
    cues: 'Push-up, then rotate open into a side plank.',
  ),
  Exercise(
    id: 'bear_hold',
    name: 'Bear Crawl Hold',
    position: ExercisePosition.bearStance,
    primary: ExerciseMuscle.coreAnterior,
    secondary: {ExerciseMuscle.shoulders},
    movements: {ExerciseMovement.hold, ExerciseMovement.plank},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.seconds,
    baseAmount: 20,
    cues: 'Knees hovering an inch off the floor, back flat.',
  ),
  Exercise(
    id: 'bear_crawl',
    name: 'Bear Crawl',
    position: ExercisePosition.bearStance,
    primary: ExerciseMuscle.fullBody,
    secondary: {ExerciseMuscle.coreAnterior, ExerciseMuscle.shoulders},
    movements: {ExerciseMovement.cardio, ExerciseMovement.plank},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Opposite hand and foot together, hips stay low.',
  ),
  Exercise(
    id: 'bear_shoulder_tap',
    name: 'Bear Stance Shoulder Taps',
    position: ExercisePosition.bearStance,
    primary: ExerciseMuscle.coreAnterior,
    secondary: {ExerciseMuscle.shoulders},
    movements: {ExerciseMovement.plank},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 16,
    cues: 'Knees hover, tap the opposite shoulder without wobbling.',
  ),
  Exercise(
    id: 'bear_knee_crunch',
    name: 'Bear Stance Knee-Tap Crunch',
    position: ExercisePosition.bearStance,
    primary: ExerciseMuscle.coreAnterior,
    movements: {ExerciseMovement.plank, ExerciseMovement.twist},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 16,
    cues: 'Knees hover, tap same-side elbow to knee under the belly.',
  ),
  Exercise(
    id: 'knee_thread_needle',
    name: 'Thread the Needle',
    position: ExercisePosition.kneeling,
    primary: ExerciseMuscle.spineMobility,
    secondary: {ExerciseMuscle.shoulders},
    movements: {ExerciseMovement.mobility, ExerciseMovement.twist},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 8,
    cues: 'From all fours, thread arm under the body, breathe into the ribs.',
  ),

  // =========================================================================
  // SIDE-LYING (7)
  // =========================================================================
  Exercise(
    id: 'side_plank',
    name: 'Side Plank',
    position: ExercisePosition.sideLying,
    primary: ExerciseMuscle.obliques,
    secondary: {ExerciseMuscle.coreAnterior},
    movements: {ExerciseMovement.plank, ExerciseMovement.hold},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Stack the shoulders, drive the hip toward the ceiling.',
  ),
  Exercise(
    id: 'side_plank_hip_dip',
    name: 'Side Plank Hip Dips',
    position: ExercisePosition.sideLying,
    primary: ExerciseMuscle.obliques,
    movements: {ExerciseMovement.plank, ExerciseMovement.twist},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Dip the hip, drive up higher than start each time.',
  ),
  Exercise(
    id: 'side_clam_shell',
    name: 'Clam Shells',
    position: ExercisePosition.sideLying,
    primary: ExerciseMuscle.glutes,
    movements: {ExerciseMovement.kick},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 15,
    cues: 'Heels together, open the top knee, hips stay stacked.',
  ),
  Exercise(
    id: 'side_leg_raise',
    name: 'Side-Lying Leg Raise',
    position: ExercisePosition.sideLying,
    primary: ExerciseMuscle.glutes,
    movements: {ExerciseMovement.kick},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 15,
    cues: 'Lift the top leg, toe slightly turned down.',
  ),
  Exercise(
    id: 'side_inner_thigh_raise',
    name: 'Inner Thigh Raise',
    position: ExercisePosition.sideLying,
    primary: ExerciseMuscle.innerThighs,
    movements: {ExerciseMovement.kick},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 15,
    cues: 'Top leg bent in front, bottom leg lifts straight.',
  ),
  Exercise(
    id: 'side_reverse_clam',
    name: 'Reverse Clam',
    position: ExercisePosition.sideLying,
    primary: ExerciseMuscle.glutes,
    movements: {ExerciseMovement.kick},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Knees stacked, lift the top foot away — knees stay together.',
  ),
  Exercise(
    id: 'side_hip_series',
    name: 'Hip Series (side)',
    position: ExercisePosition.sideLying,
    primary: ExerciseMuscle.glutes,
    secondary: {ExerciseMuscle.hipMobility},
    movements: {ExerciseMovement.kick, ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.seconds,
    baseAmount: 40,
    cues: 'Small circles, then swings — connect through the glute.',
  ),

  // =========================================================================
  // FULL BODY / CARDIO (8)
  // =========================================================================
  Exercise(
    id: 'full_mountain_climber',
    name: 'Mountain Climbers',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.fullBody,
    secondary: {ExerciseMuscle.coreAnterior},
    movements: {ExerciseMovement.cardio, ExerciseMovement.plank},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'High plank, drive knees to chest at pace.',
  ),
  Exercise(
    id: 'full_slow_climber',
    name: 'Slow Mountain Climbers',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.coreAnterior,
    secondary: {ExerciseMuscle.shoulders},
    movements: {ExerciseMovement.plank},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 16,
    cues: 'Slow tempo, place the toe, control the return.',
  ),
  Exercise(
    id: 'full_burpee',
    name: 'Burpee',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.fullBody,
    movements: {ExerciseMovement.cardio, ExerciseMovement.jump, ExerciseMovement.push},
    difficulty: ExerciseDifficulty.advanced,
    unit: ExerciseUnit.reps,
    baseAmount: 10,
    highImpact: true,
    cues: 'Down, back, push-up, up, jump. Own the tempo.',
  ),
  Exercise(
    id: 'full_half_burpee',
    name: 'Half Burpee',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.fullBody,
    movements: {ExerciseMovement.cardio, ExerciseMovement.plank},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Skip the push-up, hop feet in and out.',
  ),
  Exercise(
    id: 'full_star_jump',
    name: 'Star Jumps',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.fullBody,
    movements: {ExerciseMovement.cardio, ExerciseMovement.jump},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    highImpact: true,
    cues: 'Squat, then explode into a star, land soft.',
  ),
  Exercise(
    id: 'full_butt_kicks',
    name: 'Butt Kicks',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.hamstrings,
    secondary: {ExerciseMuscle.fullBody},
    movements: {ExerciseMovement.cardio},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Flick the heel to the glute, stay light.',
  ),
  Exercise(
    id: 'full_cross_climber',
    name: 'Cross-Body Mountain Climbers',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.obliques,
    secondary: {ExerciseMuscle.coreAnterior, ExerciseMuscle.fullBody},
    movements: {ExerciseMovement.cardio, ExerciseMovement.plank, ExerciseMovement.twist},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Drive knee to opposite elbow.',
  ),
  Exercise(
    id: 'full_inchworm',
    name: 'Inchworm',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.fullBody,
    secondary: {ExerciseMuscle.hamstrings, ExerciseMuscle.coreAnterior},
    movements: {ExerciseMovement.mobility, ExerciseMovement.plank},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 8,
    cues: 'Fold, walk out to a plank, walk back and stand.',
  ),

  // =========================================================================
  // WARM-UP POOL (18) — light, joint-forward mobility. Tagged mobility so
  // the generator can filter warm-up slots off this pool alone.
  // =========================================================================
  Exercise(
    id: 'wu_neck_rolls',
    name: 'Neck Rolls',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.spineMobility,
    movements: {ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Slow half-circles ear to shoulder, breathe through it.',
  ),
  Exercise(
    id: 'wu_shoulder_rolls',
    name: 'Shoulder Rolls',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.shoulders,
    movements: {ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Big backward circles, then forward.',
  ),
  Exercise(
    id: 'wu_side_bends',
    name: 'Standing Side Bends',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.obliques,
    secondary: {ExerciseMuscle.spineMobility},
    movements: {ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Reach the arm over, feel the side of the ribs open.',
  ),
  Exercise(
    id: 'wu_leg_swings_front',
    name: 'Leg Swings (Front)',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.hipMobility,
    movements: {ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Hold a wall, swing the leg forward and back with control.',
  ),
  Exercise(
    id: 'wu_leg_swings_side',
    name: 'Leg Swings (Side)',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.hipMobility,
    movements: {ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Swing the leg across the body, then out to the side.',
  ),
  Exercise(
    id: 'wu_ankle_circles',
    name: 'Ankle Circles',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.calves,
    movements: {ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Draw slow circles from the ankle, both directions.',
  ),
  Exercise(
    id: 'wu_wrist_circles',
    name: 'Wrist Circles',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.arms,
    movements: {ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 20,
    cues: 'Interlace fingers, circle the wrists both ways.',
  ),
  Exercise(
    id: 'wu_hip_openers',
    name: 'Standing Hip Openers',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.hipMobility,
    movements: {ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 10,
    cues: 'Knee up, open to the side, close it back. Balance through it.',
  ),
  Exercise(
    id: 'wu_world_greatest',
    name: "World's Greatest Stretch",
    position: ExercisePosition.lungeStance,
    primary: ExerciseMuscle.hipMobility,
    secondary: {ExerciseMuscle.spineMobility},
    movements: {ExerciseMovement.mobility, ExerciseMovement.lunge},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 6,
    cues: 'Deep lunge, hand inside the foot, rotate up to the ceiling.',
  ),
  Exercise(
    id: 'wu_downdog_pedals',
    name: 'Down-Dog Heel Pedals',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.calves,
    secondary: {ExerciseMuscle.hamstrings},
    movements: {ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Down-dog shape, alternate pressing each heel to the mat.',
  ),
  Exercise(
    id: 'wu_thoracic_rotation',
    name: 'Kneeling Thoracic Rotation',
    position: ExercisePosition.kneeling,
    primary: ExerciseMuscle.spineMobility,
    movements: {ExerciseMovement.mobility, ExerciseMovement.twist},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 8,
    cues: 'Hand behind head, open elbow to the ceiling, follow the eyes.',
  ),
  Exercise(
    id: 'wu_scap_pushup',
    name: 'Scap Push-Ups',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.upperBack,
    secondary: {ExerciseMuscle.shoulders},
    movements: {ExerciseMovement.mobility, ExerciseMovement.push},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 10,
    cues: 'Arms locked, only the shoulder blades move — apart and together.',
  ),
  Exercise(
    id: 'wu_glute_activation',
    name: 'Standing Glute Squeeze',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.glutes,
    movements: {ExerciseMovement.hold, ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 15,
    cues: 'Two-second squeeze, feel both glutes fire.',
  ),
  Exercise(
    id: 'wu_toe_touch_reach',
    name: 'Toe-Touch to Reach',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.spineMobility,
    secondary: {ExerciseMuscle.hamstrings},
    movements: {ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 10,
    cues: 'Fold to the toes, then unroll and reach tall overhead.',
  ),
  Exercise(
    id: 'wu_cross_toe_touch',
    name: 'Cross-body Toe Touch',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.hamstrings,
    secondary: {ExerciseMuscle.obliques},
    movements: {ExerciseMovement.mobility, ExerciseMovement.twist},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Hinge, opposite hand to opposite foot, keep the chest open.',
  ),
  Exercise(
    id: 'wu_arm_swings',
    name: 'Arm Cross-Swings',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.shoulders,
    secondary: {ExerciseMuscle.upperBack},
    movements: {ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Swing arms across the chest, then wide open.',
  ),
  Exercise(
    id: 'wu_knee_hug_walk',
    name: 'Knee Hug Marches',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.hipMobility,
    movements: {ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Pull the knee to the chest, tall through the standing leg.',
  ),
  Exercise(
    id: 'wu_shadow_jab',
    name: 'Shadow Jabs',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.shoulders,
    movements: {ExerciseMovement.cardio, ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 40,
    cues: 'Alternate jabs, stay light on your feet.',
  ),

  // =========================================================================
  // COOL-DOWN POOL (18) — long-tempo mobility and static holds. Tagged
  // mobility + hold; the generator draws cool-down slots from here.
  // =========================================================================
  Exercise(
    id: 'cd_child_pose',
    name: "Child's Pose",
    position: ExercisePosition.kneeling,
    primary: ExerciseMuscle.spineMobility,
    movements: {ExerciseMovement.hold, ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 40,
    cues: 'Big toes touch, knees wide, walk the fingertips forward.',
  ),
  Exercise(
    id: 'cd_seated_forward_fold',
    name: 'Seated Forward Fold',
    position: ExercisePosition.sitting,
    primary: ExerciseMuscle.hamstrings,
    secondary: {ExerciseMuscle.spineMobility},
    movements: {ExerciseMovement.hold, ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 40,
    cues: 'Fold from the hips, soften the knees if you need to.',
  ),
  Exercise(
    id: 'cd_butterfly',
    name: 'Butterfly Stretch',
    position: ExercisePosition.sitting,
    primary: ExerciseMuscle.innerThighs,
    secondary: {ExerciseMuscle.hipMobility},
    movements: {ExerciseMovement.hold, ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 45,
    cues: 'Soles together, hinge from the hips, breathe into the groin.',
  ),
  Exercise(
    id: 'cd_pigeon',
    name: 'Pigeon Stretch',
    position: ExercisePosition.sitting,
    primary: ExerciseMuscle.hipMobility,
    secondary: {ExerciseMuscle.glutes},
    movements: {ExerciseMovement.hold, ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.seconds,
    baseAmount: 40,
    cues: 'Front shin across, hips square, walk the hands forward.',
  ),
  Exercise(
    id: 'cd_supine_twist',
    name: 'Supine Spinal Twist',
    position: ExercisePosition.supine,
    primary: ExerciseMuscle.spineMobility,
    movements: {ExerciseMovement.hold, ExerciseMovement.twist},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 40,
    cues: 'Arms wide, drop the knees to one side, gaze the other.',
  ),
  Exercise(
    id: 'cd_hamstring_stretch',
    name: 'Supine Hamstring Stretch',
    position: ExercisePosition.supine,
    primary: ExerciseMuscle.hamstrings,
    movements: {ExerciseMovement.hold, ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 40,
    cues: 'Loop a towel round the foot, keep the leg long.',
  ),
  Exercise(
    id: 'cd_quad_stretch',
    name: 'Standing Quad Stretch',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.quads,
    movements: {ExerciseMovement.hold, ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Heel to glute, knees together, tuck the pelvis.',
  ),
  Exercise(
    id: 'cd_hip_flexor',
    name: 'Kneeling Hip Flexor Stretch',
    position: ExercisePosition.kneeling,
    primary: ExerciseMuscle.hipMobility,
    movements: {ExerciseMovement.hold, ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 40,
    cues: 'Squeeze the back glute, tuck the tailbone under.',
  ),
  Exercise(
    id: 'cd_figure_four',
    name: 'Figure-Four Stretch',
    position: ExercisePosition.supine,
    primary: ExerciseMuscle.glutes,
    secondary: {ExerciseMuscle.hipMobility},
    movements: {ExerciseMovement.hold, ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 40,
    cues: 'Ankle over knee, thread through and pull the thigh in.',
  ),
  Exercise(
    id: 'cd_cobra_hold',
    name: 'Cobra Hold',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.spineMobility,
    movements: {ExerciseMovement.hold, ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Palms under shoulders, lift the chest, shoulders soft.',
  ),
  Exercise(
    id: 'cd_downdog_hold',
    name: 'Downward Dog',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.hamstrings,
    secondary: {ExerciseMuscle.shoulders, ExerciseMuscle.calves},
    movements: {ExerciseMovement.hold, ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Hips up and back, long spine, soften the knees if needed.',
  ),
  Exercise(
    id: 'cd_thread_needle_hold',
    name: 'Thread the Needle Hold',
    position: ExercisePosition.kneeling,
    primary: ExerciseMuscle.spineMobility,
    secondary: {ExerciseMuscle.shoulders},
    movements: {ExerciseMovement.hold, ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Thread arm under, rest the shoulder, breathe into the rib.',
  ),
  Exercise(
    id: 'cd_cat_cow_slow',
    name: 'Slow Cat-Cow',
    position: ExercisePosition.kneeling,
    primary: ExerciseMuscle.spineMobility,
    movements: {ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 45,
    cues: 'Sync it to the breath — inhale arch, exhale round.',
  ),
  Exercise(
    id: 'cd_box_breath',
    name: 'Box Breathing',
    position: ExercisePosition.sitting,
    primary: ExerciseMuscle.coreAnterior,
    movements: {ExerciseMovement.hold, ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 60,
    cues: 'Inhale 4, hold 4, exhale 4, hold 4. Repeat.',
  ),
  Exercise(
    id: 'cd_chest_opener',
    name: 'Standing Chest Opener',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.chest,
    secondary: {ExerciseMuscle.shoulders},
    movements: {ExerciseMovement.hold, ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Interlace hands behind you, lift and open the chest.',
  ),
  Exercise(
    id: 'cd_calf_stretch',
    name: 'Wall Calf Stretch',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.calves,
    movements: {ExerciseMovement.hold, ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Back heel down, front knee bent — push into the wall.',
  ),
  Exercise(
    id: 'cd_neck_stretch',
    name: 'Seated Neck Stretch',
    position: ExercisePosition.sitting,
    primary: ExerciseMuscle.spineMobility,
    movements: {ExerciseMovement.hold, ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Ear to shoulder, opposite hand can add gentle weight.',
  ),
  Exercise(
    id: 'cd_savasana',
    name: 'Rest & Reset',
    position: ExercisePosition.supine,
    primary: ExerciseMuscle.fullBody,
    movements: {ExerciseMovement.hold, ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 60,
    cues: 'Long exhale. Feel the work land in the body.',
  ),

  // =========================================================================
  // EXTRA MAIN VARIANTS (30) — gives the 21-day plan enough breadth that
  // the same 12-slot main block never repeats verbatim two days running.
  // =========================================================================
  Exercise(
    id: 'main_squat_pulse_hold',
    name: 'Low Squat Pulse Hold',
    position: ExercisePosition.squatStance,
    primary: ExerciseMuscle.quads,
    secondary: {ExerciseMuscle.glutes},
    movements: {ExerciseMovement.squat, ExerciseMovement.hold},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.seconds,
    baseAmount: 35,
    cues: 'Stay low, tiny two-inch pulses without standing up.',
  ),
  Exercise(
    id: 'main_squat_thrust',
    name: 'Squat Thrusts',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.fullBody,
    movements: {ExerciseMovement.cardio, ExerciseMovement.squat},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Squat, kick feet back to a plank, jump them in, stand.',
  ),
  Exercise(
    id: 'main_glute_kickback',
    name: 'Standing Glute Kickback',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.glutes,
    movements: {ExerciseMovement.kick, ExerciseMovement.hinge},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 16,
    cues: 'Hinge slightly, drive the heel straight back, squeeze.',
  ),
  Exercise(
    id: 'main_curtsy_kick',
    name: 'Curtsy Lunge to Kick',
    position: ExercisePosition.lungeStance,
    primary: ExerciseMuscle.glutes,
    secondary: {ExerciseMuscle.obliques},
    movements: {ExerciseMovement.lunge, ExerciseMovement.kick},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 10,
    cues: 'Curtsy behind, drive the back leg out to the side.',
  ),
  Exercise(
    id: 'main_glute_bridge_march',
    name: 'Bridge with March',
    position: ExercisePosition.supine,
    primary: ExerciseMuscle.glutes,
    secondary: {ExerciseMuscle.coreAnterior},
    movements: {ExerciseMovement.hold, ExerciseMovement.hinge},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Hold the bridge high, alternate lifting one foot at a time.',
  ),
  Exercise(
    id: 'main_frog_pump',
    name: 'Frog Pumps',
    position: ExercisePosition.supine,
    primary: ExerciseMuscle.glutes,
    movements: {ExerciseMovement.hinge},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 20,
    cues: 'Soles together, knees drop out, drive the hips up.',
  ),
  Exercise(
    id: 'main_side_lunge_reach',
    name: 'Side Lunge with Reach',
    position: ExercisePosition.lungeStance,
    primary: ExerciseMuscle.innerThighs,
    secondary: {ExerciseMuscle.obliques},
    movements: {ExerciseMovement.lunge, ExerciseMovement.mobility},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Step out, sit into the bent hip, opposite hand reaches over.',
  ),
  Exercise(
    id: 'main_pushup_reach',
    name: 'Push-Up to Reach',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.chest,
    secondary: {ExerciseMuscle.obliques, ExerciseMuscle.shoulders},
    movements: {ExerciseMovement.push, ExerciseMovement.twist},
    difficulty: ExerciseDifficulty.advanced,
    unit: ExerciseUnit.reps,
    baseAmount: 8,
    cues: 'Push-up, then rotate open and reach one arm to the sky.',
  ),
  Exercise(
    id: 'main_pushup_hold',
    name: 'Push-Up Bottom Hold',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.chest,
    secondary: {ExerciseMuscle.arms},
    movements: {ExerciseMovement.hold, ExerciseMovement.push},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.seconds,
    baseAmount: 15,
    cues: 'Hover an inch off the mat, elbows in, keep breathing.',
  ),
  Exercise(
    id: 'main_negative_pushup',
    name: 'Negative Push-Ups',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.chest,
    movements: {ExerciseMovement.push},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 8,
    cues: 'Lower on a slow 4-count, drop knees, reset up.',
  ),
  Exercise(
    id: 'main_high_plank',
    name: 'High Plank Hold',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.coreAnterior,
    secondary: {ExerciseMuscle.shoulders},
    movements: {ExerciseMovement.plank, ExerciseMovement.hold},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Wrists under shoulders, ribs down, glutes on.',
  ),
  Exercise(
    id: 'main_plank_reach',
    name: 'Plank Alt-Reach',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.coreAnterior,
    secondary: {ExerciseMuscle.shoulders},
    movements: {ExerciseMovement.plank},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 16,
    cues: 'From high plank, reach one arm forward. Hips stay still.',
  ),
  Exercise(
    id: 'main_plank_knee_taps',
    name: 'Plank Knee Taps',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.coreAnterior,
    movements: {ExerciseMovement.plank},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 20,
    cues: 'From high plank, tap the knee to the mat, control the return.',
  ),
  Exercise(
    id: 'main_side_plank_lift',
    name: 'Side Plank Leg Lift',
    position: ExercisePosition.sideLying,
    primary: ExerciseMuscle.obliques,
    secondary: {ExerciseMuscle.glutes},
    movements: {ExerciseMovement.plank, ExerciseMovement.kick},
    difficulty: ExerciseDifficulty.advanced,
    unit: ExerciseUnit.reps,
    baseAmount: 10,
    cues: 'From a side plank, lift the top leg. Hips high.',
  ),
  Exercise(
    id: 'main_dead_bug_holds',
    name: 'Dead Bug Holds',
    position: ExercisePosition.supine,
    primary: ExerciseMuscle.coreAnterior,
    movements: {ExerciseMovement.hold, ExerciseMovement.plank},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Opposite arm and leg extend, hold, slowly return.',
  ),
  Exercise(
    id: 'main_toe_touch_cross',
    name: 'Cross-Body Toe Touch (Supine)',
    position: ExercisePosition.supine,
    primary: ExerciseMuscle.obliques,
    movements: {ExerciseMovement.plank, ExerciseMovement.twist},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 16,
    cues: 'Legs up, opposite fingertip to opposite toe.',
  ),
  Exercise(
    id: 'main_seated_twist_reach',
    name: 'Seated Twist Reach',
    position: ExercisePosition.sitting,
    primary: ExerciseMuscle.obliques,
    movements: {ExerciseMovement.twist},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 20,
    cues: 'Lean back 30°, rotate ribs, reach across the body.',
  ),
  Exercise(
    id: 'main_knee_drive',
    name: 'Standing Knee Drives',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.coreAnterior,
    secondary: {ExerciseMuscle.fullBody},
    movements: {ExerciseMovement.cardio, ExerciseMovement.kick},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 40,
    cues: 'Drive one knee up, elbows crunch down. Alternate.',
  ),
  Exercise(
    id: 'main_squat_kick',
    name: 'Squat to Front Kick',
    position: ExercisePosition.squatStance,
    primary: ExerciseMuscle.quads,
    secondary: {ExerciseMuscle.glutes, ExerciseMuscle.coreAnterior},
    movements: {ExerciseMovement.squat, ExerciseMovement.kick},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 14,
    cues: 'Squat, then explode into a front kick as you stand.',
  ),
  Exercise(
    id: 'main_squat_press',
    name: 'Squat to Overhead Reach',
    position: ExercisePosition.squatStance,
    primary: ExerciseMuscle.quads,
    secondary: {ExerciseMuscle.shoulders},
    movements: {ExerciseMovement.squat, ExerciseMovement.push},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.reps,
    baseAmount: 15,
    cues: 'Squat, drive up, press arms overhead.',
  ),
  Exercise(
    id: 'main_speed_skater',
    name: 'Speed Skaters',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.glutes,
    secondary: {ExerciseMuscle.fullBody},
    movements: {ExerciseMovement.cardio, ExerciseMovement.jump},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.seconds,
    baseAmount: 35,
    highImpact: true,
    cues: 'Bound side to side, opposite arm swings through.',
  ),
  Exercise(
    id: 'main_low_impact_climber',
    name: 'Slider Climbers',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.coreAnterior,
    secondary: {ExerciseMuscle.fullBody},
    movements: {ExerciseMovement.plank, ExerciseMovement.cardio},
    difficulty: ExerciseDifficulty.beginner,
    unit: ExerciseUnit.seconds,
    baseAmount: 40,
    cues: 'From a plank, slide each foot in and out with control.',
  ),
  Exercise(
    id: 'main_reverse_plank',
    name: 'Reverse Plank',
    position: ExercisePosition.sitting,
    primary: ExerciseMuscle.glutes,
    secondary: {ExerciseMuscle.lowerBack, ExerciseMuscle.hamstrings},
    movements: {ExerciseMovement.hold, ExerciseMovement.plank},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.seconds,
    baseAmount: 25,
    cues: 'Hands under shoulders, drive hips up, chest tall.',
  ),
  Exercise(
    id: 'main_reverse_plank_kick',
    name: 'Reverse Plank Leg Kicks',
    position: ExercisePosition.sitting,
    primary: ExerciseMuscle.glutes,
    secondary: {ExerciseMuscle.coreAnterior},
    movements: {ExerciseMovement.hold, ExerciseMovement.kick},
    difficulty: ExerciseDifficulty.advanced,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Hold the reverse plank, alternate lifting the legs.',
  ),
  Exercise(
    id: 'main_wall_hold_pulses',
    name: 'Wall Sit Pulses',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.quads,
    secondary: {ExerciseMuscle.glutes},
    movements: {ExerciseMovement.hold, ExerciseMovement.squat},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'Wall sit, tiny pulses without leaving the wall.',
  ),
  Exercise(
    id: 'main_pushup_shoulder_tap',
    name: 'Push-Up to Shoulder Tap',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.chest,
    secondary: {ExerciseMuscle.coreAnterior},
    movements: {ExerciseMovement.push, ExerciseMovement.plank},
    difficulty: ExerciseDifficulty.advanced,
    unit: ExerciseUnit.reps,
    baseAmount: 8,
    cues: 'Push-up, then tap each shoulder at the top. Hips still.',
  ),
  Exercise(
    id: 'main_reverse_lunge_kick',
    name: 'Reverse Lunge to Knee Drive',
    position: ExercisePosition.lungeStance,
    primary: ExerciseMuscle.glutes,
    secondary: {ExerciseMuscle.coreAnterior},
    movements: {ExerciseMovement.lunge, ExerciseMovement.kick},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 12,
    cues: 'Step back long, drive that knee up as you stand.',
  ),
  Exercise(
    id: 'main_deadlift_reach',
    name: 'Single-Leg Deadlift Reach',
    position: ExercisePosition.standing,
    primary: ExerciseMuscle.hamstrings,
    secondary: {ExerciseMuscle.glutes, ExerciseMuscle.coreAnterior},
    movements: {ExerciseMovement.hinge},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 10,
    cues: 'Hinge over the standing leg, back leg long, spine flat.',
  ),
  Exercise(
    id: 'main_bicycle_slow',
    name: 'Slow Bicycle',
    position: ExercisePosition.supine,
    primary: ExerciseMuscle.obliques,
    secondary: {ExerciseMuscle.coreAnterior},
    movements: {ExerciseMovement.twist},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.reps,
    baseAmount: 20,
    cues: 'Slow tempo — pause each rep at the peak of the twist.',
  ),
  Exercise(
    id: 'main_dynamic_plank',
    name: 'Plank In-Outs',
    position: ExercisePosition.prone,
    primary: ExerciseMuscle.coreAnterior,
    secondary: {ExerciseMuscle.fullBody},
    movements: {ExerciseMovement.plank, ExerciseMovement.cardio},
    difficulty: ExerciseDifficulty.intermediate,
    unit: ExerciseUnit.seconds,
    baseAmount: 30,
    cues: 'From plank, hop feet wide, then back in.',
  ),
];
